version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Postgres123}
    healthcheck:
      test: "pg_isready -U postgres"
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    environment:
      - KC_HOSTNAME=${HOSTNAME:-localhost}
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=${POSTGRES_DB:-postgres}
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=${POSTGRES_USER:-postgres}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-Postgres123}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-Admin123}
      # Use when behind load balancer with SSL
      # - KC_PROXY=edge
    ports:
      - "8443:8443"
      # Use when behind load balancer with SSL
      #- "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: curl --head -fsS http://localhost:8080/health/live || exit 1
  postfix:
    build:
      context: postfix
      dockerfile: Dockerfile
    environment:
      - POSTFIX_HOSTNAME=${POSTFIX_HOSTNAME:-localhost}
      - POSTFIX_MYNETWORKS=${POSTFIX_MYNETWORKS:-172.17.0.0/24}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-username}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-password}
      - LDAP_HOST=${LDAP_HOST:-openldap}
      - LDAP_PORT=${LDAP_PORT:-389}
volumes:
  postgres_data:
    driver: local
